# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-05 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='myblog/images', max_length=255),
        ),
    ]
